apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: riosapp-certificate
  namespace: default
spec:
  secretName: mysite-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: riosapp.jason-suarez.com
  dnsNames:
  - riosapp.jason-suarez.com
