version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    environment:
      - PUBG_API_KEY=${PUBG_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./
          target: /var/www/html
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    user: root
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
volumes:
  db_data:
secrets:
  db-password:
    file: db/password.txt
