apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: riosapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "riosapp.jason-suarez.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: riosapp-service
            port:
              number: 80
